[tool.black]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_gitignore = true
lines_between_types = 1

[tool.poetry]
name = "retry-task-lib"
version = "1.0.0"
description = "helpers functions and models for setting up tasks with rq"
authors = ["Francesco Milani <fmilani@bink.com>"]

[tool.poetry.dependencies]
python = "^3.9"
rq = "^1.10.0"
SQLAlchemy = "^1.4.25"
requests = "^2.26.0"
sentry-sdk = "^1.4.3"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.9.3"
flake8 = "^3.9.2"
mypy = "^0.910"
xenon = "^0.8.0"
types-requests = "^2.25.9"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-asyncio = "^0.15.1"
pytest-mock = "^3.6.1"
ipython = "^7.28.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
