name: ci

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  pull_request:
    branches: [master]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://postgres@127.0.0.1:5432/retry_tasks_lib_test"
      REDIS_URL: redis://127.0.0.1:6379/0
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: retry_tasks_lib_test
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install -E admin -E reporting
      - run: xenon --no-assert --max-average A --max-modules B --max-absolute B .
      - run: black --check .
      - run: isort --check .
      - run: mypy .
      - run: ruff retry_tasks_lib tests
      - run: refurb retry_tasks_lib tests
      - run: pytest tests --verbose --cov=retry_tasks_lib --cov-report=xml --junitxml=report.xml
  release:
    if: github.event_name == 'push'
    name: release
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry self add "poetry-dynamic-versioning[plugin]"
      - run: poetry config repositories.azure https://pkgs.dev.azure.com/binkhq/_packaging/binkhq/pypi/upload/
      - run: poetry config http-basic.azure jeff ${{ secrets.AZURE_DEVOPS_PAT }}
      - run: poetry build
      - run: poetry publish -r azure
